/* Auto-generated by tools/vendor_worlds.py — do not edit.
   Locally vendored Marble assets. Their presence is what lets the
   public site serve these worlds with no API key: worldlabs.js
   returns a synthetic world object instead of calling the API. */
window.LSC_WORLDS_LOCAL = {
  "temple-bar": {
    "spz_urls": {
      "100k": "worlds/temple-bar/splat-100k.spz",
      "500k": "worlds/temple-bar/splat-500k.spz"
    },
    "pano_url": "worlds/temple-bar/pano.png",
    "collider_mesh_url": "worlds/temple-bar/collider.glb",
    "thumbnail_url": "worlds/temple-bar/thumb.webp"
  },
  "grafton-street": {
    "spz_urls": {
      "100k": "worlds/grafton-street/splat-100k.spz",
      "500k": "worlds/grafton-street/splat-500k.spz"
    },
    "pano_url": "worlds/grafton-street/pano.png",
    "collider_mesh_url": "worlds/grafton-street/collider.glb",
    "thumbnail_url": "worlds/grafton-street/thumb.webp"
  },
  "lighthouse-cinema": {
    "spz_urls": {
      "100k": "worlds/lighthouse-cinema/splat-100k.spz",
      "500k": "worlds/lighthouse-cinema/splat-500k.spz"
    },
    "pano_url": "worlds/lighthouse-cinema/pano.png",
    "collider_mesh_url": "worlds/lighthouse-cinema/collider.glb",
    "thumbnail_url": "worlds/lighthouse-cinema/thumb.webp"
  },
  "croke-park": {
    "spz_urls": {
      "100k": "worlds/croke-park/splat-100k.spz",
      "500k": "worlds/croke-park/splat-500k.spz"
    },
    "pano_url": "worlds/croke-park/pano.png",
    "collider_mesh_url": "worlds/croke-park/collider.glb",
    "thumbnail_url": "worlds/croke-park/thumb.webp"
  },
  "stephens-green": {
    "spz_urls": {
      "100k": "worlds/stephens-green/splat-100k.spz",
      "500k": "worlds/stephens-green/splat-500k.spz"
    },
    "pano_url": "worlds/stephens-green/pano.png",
    "collider_mesh_url": "worlds/stephens-green/collider.glb",
    "thumbnail_url": "worlds/stephens-green/thumb.webp"
  },
  "hapenny-bridge": {
    "spz_urls": {
      "100k": "worlds/hapenny-bridge/splat-100k.spz",
      "500k": "worlds/hapenny-bridge/splat-500k.spz"
    },
    "pano_url": "worlds/hapenny-bridge/pano.png",
    "collider_mesh_url": "worlds/hapenny-bridge/collider.glb",
    "thumbnail_url": "worlds/hapenny-bridge/thumb.webp"
  },
  "the-spire": {
    "spz_urls": {
      "100k": "worlds/the-spire/splat-100k.spz",
      "500k": "worlds/the-spire/splat-500k.spz"
    },
    "pano_url": "worlds/the-spire/pano.png",
    "collider_mesh_url": "worlds/the-spire/collider.glb",
    "thumbnail_url": "worlds/the-spire/thumb.webp"
  },
  "liffey-quays": {
    "spz_urls": {
      "100k": "worlds/liffey-quays/splat-100k.spz",
      "500k": "worlds/liffey-quays/splat-500k.spz"
    },
    "pano_url": "worlds/liffey-quays/pano.png",
    "collider_mesh_url": "worlds/liffey-quays/collider.glb",
    "thumbnail_url": "worlds/liffey-quays/thumb.webp"
  }
};
